name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: cd api && npm ci && npm run lint && npm test
      - run: cd ../app && npm ci && npm run lint && npm test